name: Test and deploy

on:
  push:
    branches:
      - master
      - develop
    tags:
      - "*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Run tests
        run: sbt coverage +test coverageReport

      - name: Aggregate coverage data
        run: sbt coverageAggregate

      - name: Aggregate coverage data and submit
        run: sbt coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: sbt "project core" ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.SONA_PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.SONA_PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONA_PASS }}
          SONATYPE_USERNAME: snowplow
      - name: Publish ScalaDoc
        run: |
            sbt "project core" makeSite
            echo Publishing Scaladoc
            git fetch
            git checkout gh-pages
            cp -r modules/core/target/site/* .
            git config user.name "GitHub Actions"
            git config user.email "<>"
            git add $GITHUB_REF
            git commit -m "Added Scaladoc for $GITHUB_REF"
            git push origin gh-pages
